### ISSUE TITLE
To Do list

### ISSUE THREAD

**Issue by tmrhombus** [DisplacedHiggs/LLDJstandalones#56]
# Current: tt ntuples

copied over from https://docs.google.com/document/d/1t3jG_ErTo4FzH6Y5T0t0x3_L9NPPx5h4sqeCzFjlnrs/edit

 # Wish List
Primary vertex info for PU reweighting 
Photon triggers
 ## Photons:
pat::photon->passElectronVeto()
pat::photon->hasPixelSeed()
 ## Muons:
Fix bug in muon impact parameter variables https://github.com/DisplacedHiggs/LLDJstandalones/blob/master/ntuples/plugins/lldjNtuple_AODmuons.cc#L151-L155 need to fill with dummy value when no inner track!
 ## AOD calo jets
Number of matched tracks without cleaning requirement

**Comment by benjaminkreis** [comment]
# Current: addpu 

# Wish list

## Electrons
- Accept PR for d0 and dz addition to ntuple maker and add cuts on these in analyzer

## Photons:
- Photon triggers
- We believe pat::photon->passElectronVeto() is not needed

**Comment by tmrhombus** [comment]
+ prescale info
+ CSV info for PF(chs) jets

**Comment by benjaminkreis** [comment]
gen level flavor

**Comment by benjaminkreis** [comment]
PF jet parton flavour

**Comment by benjaminkreis** [comment]
Recent PRs have covered pf jet parton flavour and b tagging results, prescale info, photon and mu+eg triggers, and prescale info
